package com.deniscerri.ytdl.util

import com.deniscerri.ytdl.database.models.CookieItem
import java.io.File
import java.util.Locale

/** Builds a compact master cookie jar and private snapshots for concurrent downloads. */
object CookieFileUtil {
    private const val SESSION_DIRECTORY = "cookie_sessions"
    private const val NETSCAPE_HEADER =
        "# Netscape HTTP Cookie File\n" +
            "# WebView Generated by the YTDLnis app\n" +
            "# This is a generated file! Do not edit.\n"

    /** The first duplicate wins because enabled imports are returned newest-first. */
    fun merge(
        cookieItems: List<CookieItem>,
        nowEpochSeconds: Long = System.currentTimeMillis() / 1000,
    ): String {
        val cookies = linkedMapOf<String, String>()

        cookieItems.forEach { item ->
            item.content.lineSequence().forEach lineLoop@{ sourceLine ->
                val line = sourceLine.trimEnd('\r')
                if (line.isBlank()) return@lineLoop
                if (line.startsWith("#") && !line.startsWith("#HttpOnly_")) return@lineLoop

                val fields = line.split('\t', limit = 7)
                if (fields.size != 7) return@lineLoop

                val expiresAt = fields[4].toLongOrNull()
                if (expiresAt != null && expiresAt > 0 && expiresAt <= nowEpochSeconds) {
                    return@lineLoop
                }

                val normalizedDomain = fields[0]
                    .removePrefix("#HttpOnly_")
                    .lowercase(Locale.ROOT)
                val key = "$normalizedDomain\u0000${fields[2]}\u0000${fields[5]}"
                cookies.putIfAbsent(key, line)
            }
        }

        return buildString {
            append(NETSCAPE_HEADER)
            cookies.values.forEach {
                append(it)
                append('\n')
            }
        }
    }

    /** Atomically replaces the jar only when its content actually changed. */
    fun writeAtomicallyIfChanged(target: File, content: String): Boolean {
        if (target.exists() && target.readText() == content) return false

        target.parentFile?.mkdirs()
        val temporary = File(target.parentFile, ".${target.name}.tmp")
        temporary.writeText(content)
        try {
            if (!temporary.renameTo(target)) temporary.copyTo(target, overwrite = true)
        } finally {
            temporary.delete()
        }
        return true
    }

    fun createSessionCopy(cacheDirectory: File, source: File, downloadId: Long): File {
        val sessionDirectory = File(cacheDirectory, SESSION_DIRECTORY).apply { mkdirs() }
        val sessionFile = File(sessionDirectory, "$downloadId.txt")
        val temporary = File(sessionDirectory, ".$downloadId.tmp")
        try {
            source.copyTo(temporary, overwrite = true)
            if (!temporary.renameTo(sessionFile)) temporary.copyTo(sessionFile, overwrite = true)
            sessionFile.setReadable(false, false)
            sessionFile.setWritable(false, false)
            sessionFile.setReadable(true, true)
            sessionFile.setWritable(true, true)
        } finally {
            temporary.delete()
        }
        return sessionFile
    }

    fun deleteSessionCopy(cacheDirectory: File, downloadId: Long) {
        File(File(cacheDirectory, SESSION_DIRECTORY), "$downloadId.txt").delete()
    }

    fun deleteAllSessionCopies(cacheDirectory: File) {
        File(cacheDirectory, SESSION_DIRECTORY).deleteRecursively()
    }
}
