name: Android CI

env:
  main_project_module: app

permissions: {}

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'corretto'
          cache: 'gradle'

      - name: Configure Keystore & Properties
        run: |
          echo "${{ secrets.BASE_64_SIGNING_KEY }}" | base64 -d > app/release_keystore.jks
          touch local.properties
          echo "${{ secrets.LOCAL_PROPERTIES }}" > keystore.properties
          chmod +x gradlew

      - name: Build APK release projects
        run: ./gradlew assembleGithubRelease assembleFossRelease assembleIzzyRelease --warning-mode all

      # --- GITHUB FLAVOR ---
      - name: Upload GitHub arm64
        uses: actions/upload-artifact@v4
        with:
          name: ytdlnis-autogenerated-arm64-v8a-release
          path: ${{ env.main_project_module }}/build/outputs/apk/github/release/*arm64*.apk

      - name: Upload GitHub armeabiv7
        uses: actions/upload-artifact@v4
        with:
          name: ytdlnis-autogenerated-armeabi-v7a-release
          path: ${{ env.main_project_module }}/build/outputs/apk/github/release/*armeabi*.apk

      - name: Upload GitHub universal
        uses: actions/upload-artifact@v4
        with:
          name: ytdlnis-autogenerated-universal-release
          path: ${{ env.main_project_module }}/build/outputs/apk/github/release/*universal*.apk

      - name: Upload GitHub x86
        uses: actions/upload-artifact@v4
        with:
          name: ytdlnis-autogenerated-x86-release
          path: ${{ env.main_project_module }}/build/outputs/apk/github/release/*x86-*.apk

      - name: Upload GitHub x86_64
        uses: actions/upload-artifact@v4
        with:
          name: ytdlnis-autogenerated-x86_64-release
          path: ${{ env.main_project_module }}/build/outputs/apk/github/release/*x86_64*.apk

      - name: Upload Full Github Folder
        uses: actions/upload-artifact@v4
        with:
          name: YTDLnis APK release generated
          path: ${{ env.main_project_module }}/build/outputs/apk/github/release/

      # --- FOSS FLAVOR ---
      - name: Upload FOSS arm64
        uses: actions/upload-artifact@v4
        with:
          name: ytdlnis-autogenerated-arm64-v8a-foss-release
          path: ${{ env.main_project_module }}/build/outputs/apk/foss/release/*arm64*.apk

      - name: Upload FOSS armeabiv7
        uses: actions/upload-artifact@v4
        with:
          name: ytdlnis-autogenerated-armeabi-v7a-foss-release
          path: ${{ env.main_project_module }}/build/outputs/apk/foss/release/*armeabi*.apk

      - name: Upload FOSS universal
        uses: actions/upload-artifact@v4
        with:
          name: ytdlnis-autogenerated-universal-foss-release
          path: ${{ env.main_project_module }}/build/outputs/apk/foss/release/*universal*.apk

      - name: Upload FOSS x86
        uses: actions/upload-artifact@v4
        with:
          name: ytdlnis-autogenerated-x86-foss-release
          path: ${{ env.main_project_module }}/build/outputs/apk/foss/release/*x86-*.apk

      - name: Upload FOSS x86_64
        uses: actions/upload-artifact@v4
        with:
          name: ytdlnis-autogenerated-x86_64-foss-release
          path: ${{ env.main_project_module }}/build/outputs/apk/foss/release/*x86_64*.apk

      - name: Upload Full FOSS Folder
        uses: actions/upload-artifact@v4
        with:
          name: YTDLnis APK release FOSS generated
          path: ${{ env.main_project_module }}/build/outputs/apk/foss/release/

      # --- IZZY FLAVOR ---
      - name: Upload Izzy arm64
        uses: actions/upload-artifact@v4
        with:
          name: ytdlnis-autogenerated-arm64-v8a-izzy-release
          path: ${{ env.main_project_module }}/build/outputs/apk/izzy/release/*arm64*.apk

      - name: Upload Izzy armeabiv7
        uses: actions/upload-artifact@v4
        with:
          name: ytdlnis-autogenerated-armeabi-v7a-izzy-release
          path: ${{ env.main_project_module }}/build/outputs/apk/izzy/release/*armeabi*.apk

      - name: Upload Izzy universal
        uses: actions/upload-artifact@v4
        with:
          name: ytdlnis-autogenerated-universal-izzy-release
          path: ${{ env.main_project_module }}/build/outputs/apk/izzy/release/*universal*.apk

      - name: Upload Izzy x86
        uses: actions/upload-artifact@v4
        with:
          name: ytdlnis-autogenerated-x86-izzy-release
          path: ${{ env.main_project_module }}/build/outputs/apk/izzy/release/*x86-*.apk

      - name: Upload Izzy x86_64
        uses: actions/upload-artifact@v4
        with:
          name: ytdlnis-autogenerated-x86_64-izzy-release
          path: ${{ env.main_project_module }}/build/outputs/apk/izzy/release/*x86_64*.apk

      - name: Upload Full Izzy Folder
        uses: actions/upload-artifact@v4
        with:
          name: YTDLnis APK release Izzy generated
          path: ${{ env.main_project_module }}/build/outputs/apk/izzy/release/

      # --- TELEGRAM ---
      - name: Send Telegram Message
        continue-on-error: true
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            Repository: ${{ github.repository }}
            See changes: https://github.com/${{ github.repository }}/commit/${{ github.sha }}