package com.deniscerri.ytdl.database.repository

import android.app.Application
import com.deniscerri.ytdl.database.dao.CookieDao
import com.deniscerri.ytdl.database.models.CookieItem
import com.deniscerri.ytdl.util.FileUtil
import kotlinx.coroutines.flow.Flow
import java.io.File

class CookieRepository(private val cookieDao: CookieDao, private val application: Application) {

    val items : Flow<List<CookieItem>> = cookieDao.getAllCookiesFlow()

    fun getAll() : List<CookieItem> {
        return cookieDao.getAllCookies()
    }

    fun getAllEnabled() : List<CookieItem> {
        return cookieDao.getAllEnabledCookies()
    }

    fun getByURL(url: String) : CookieItem? {
        return cookieDao.getByURL(url)
    }

    fun getByURLDescription(url: String, description: String) : CookieItem? {
        return cookieDao.getByURLDescription(url, description)
    }


    suspend fun insert(item: CookieItem) : Long {
        return cookieDao.insert(item)
    }

    suspend fun delete(item: CookieItem){
        cookieDao.delete(item.id)
    }

    suspend fun changeCookieEnabledState(itemId: Long, isEnabled: Boolean) {
        cookieDao.changeEnabledState(itemId, isEnabled)
    }


    suspend fun deleteAll(){
        cookieDao.deleteAll()
    }

    suspend fun update(item: CookieItem){
        cookieDao.update(item)
    }

    fun updateCookieFile() {
        val cookies = getAllEnabled()
        val cookieTXT = StringBuilder(cookieHeader)
        FileUtil.getCookieFile(application, true){ c ->
            val cookieFile = File(c)
            if (cookies.isEmpty()) cookieFile.apply { writeText("") }
            cookies.forEach {
                it.content.lines().forEach {line ->
                    if (! cookieTXT.contains(line)) cookieTXT.append(it.content)
                }
            }
            cookieFile.apply { writeText(cookieTXT.toString()) }
        }

        //clear info jsons after updating cookies
        val infoJsonPath = FileUtil.getInfoJsonPath(application)
        File(infoJsonPath).deleteRecursively()
    }

    companion object {
        val cookieHeader =
            "# Netscape HTTP Cookie File\n" +
                    "# WebView Generated by the YTDLnis app\n" +
                    "# This is a generated file! Do not edit."
    }
}